// Generated by CoffeeScript 1.9.3
(function() {
  var Test, extend, log, request, util;

  util = require('util');

  request = require('request-json');

  extend = require('util')._extend;

  log = require('./utils/logger').getLogger();

  log.info("Test - Logger test message");

  Test = (function() {
    function Test(data) {
      this.config = extend({}, data);
      this.statistics = {};
      this.status = {};
      log.info("Test object created with  " + JSON.stringify(this.config));
    }

    Test.prototype.start = function(callback) {
      var client;
      log.info("starting a test " + JSON.stringify(this.config));
      this.URL = "http://" + this.config.source + ":5051";
      log.info("Agent url is " + this.URL);
      client = request.newClient(this.URL);
      return client.post('/Test', this.config, (function(_this) {
        return function(err, res, body) {
          if (err != null) {
            log.info("err" + JSON.stringify(err));
          }
          log.info("start test result " + JSON.stringify(body));
          _this.uuid = body.id;
          return callback(_this.body);
        };
      })(this));
    };

    Test.prototype.run = function(callback) {
      return this.start((function(_this) {
        return function(result) {
          return callback(result);
        };
      })(this));
    };

    Test.prototype.get = function(callback) {
      var client;
      client = request.newClient(this.URL);
      return client.get("/Test/" + this.uuid, (function(_this) {
        return function(err, res, body) {
          if (err != null) {
            log.info("err" + JSON.stringify(err));
          }
          log.info("get test result " + JSON.stringify(body));
          _this.status = body;
          return callback(body);
        };
      })(this));
    };

    return Test;

  })();


  /*
      create : (callback)->
          log.info "c node " + JSON.stringify @config
  
          vmctrl.create @config, (result) =>
              @uuid = result.id
              @config.id = @uuid
              @status.result = result.status
              @status.result = result.reason if result.reason?
              log.info "node creation result " + JSON.stringify result
              callback result
  
  
      stop : (callback)->
          log.info "stopping a node " + @config.name
          vmctrl.stop @uuid, (result) =>
              log.info "node stop result " + JSON.stringify result            
              callback result
  
      del : (callback)->
          log.info "node deleting  " + @config.name
          vmctrl.del @uuid, (res) =>
              log.info "node del result " + JSON.stringify res            
              callback res    
      getstatus : (callback)->
          log.info "getstatus called" + @uuid
          vmctrl.get @uuid, (result) =>
              log.info "node getstatus result " + JSON.stringify result
              callback result
      getrunningstatus : (callback)->
          vmctrl.status @params.id, (res) =>
              log.info "node running status result " +  res
              callback res  
      get : () ->
          "id" : @uuid
          "config": @config
          #"status": @status
          #"statistics":@statistics
   */

  module.exports = Test;

}).call(this);
