// Generated by CoffeeScript 1.9.3
var config, dpkgquery, exec, i, j, k, len, len1, len2, pack1, pack2, pack3, ref, ref1, ref2, util;

util = require('util');

exec = require('child_process').exec;

dpkgquery = function(command, callback) {
  if (command == null) {
    callback(false);
  }
  command = "dpkg-query -s " + command;
  util.log("executing " + command + "...");
  return exec(command, (function(_this) {
    return function(error, stdout, stderr) {
      if (error != null) {
        return callback(false);
      } else {
        return callback(true);
      }
    };
  })(this));
};

config = require('../package.json').config;

console.log("==========================================================");

ref = config.debianpackages.virtualization.lxc;
for (i = 0, len = ref.length; i < len; i++) {
  pack1 = ref[i];
  dpkgquery(pack1, function(result) {
    return console.log((pack1 + "  :  ") + result);
  });
}

ref1 = config.debianpackages["switch"].linuxbridge;
for (j = 0, len1 = ref1.length; j < len1; j++) {
  pack2 = ref1[j];
  dpkgquery(pack2, function(result) {
    return console.log((pack2 + "    : ") + result);
  });
}

ref2 = config.debianpackages["switch"].openvswitch;
for (k = 0, len2 = ref2.length; k < len2; k++) {
  pack3 = ref2[k];
  dpkgquery(pack3, function(result) {
    return console.log((pack3 + "    : ") + result);
  });
}

console.log("==========================================================");
