// Generated by CoffeeScript 1.9.3
(function() {
  var message;

  message = "----------------------------------------------------------------\n lxc , openvswitch, bridgeutils  debian packages are needed to run the KaanalNet.\n During this nodejs package installation,  \n 1. lxc, bridgeutils, openvswitch debian packages will be installed. \n 2. lxc ubuntu base image will be installed\n This installation will take  approximately 30-45 mins to complete (depends on your internet speed) \n -----------------------------------------------------------------\n";

  console.log("**************  IMPORTANT NOTE  ***************");

  console.log(message);

  console.log("***********************************************");

}).call(this);
