// Generated by CoffeeScript 1.9.3
var message;

message = "\n----------------------------------------------------------------\n lxc , openvswitch  packages are needed to run the KaanalNet.\n During this installation,  \n 1. lxc and  openvswitch will be installed. \n 2. Base lxc ubuntu image will be installed\n -----------------------------------------------------------------\n";

console.log("**************  IMPORTANT NOTE  ***************");

console.log(message);
