// Generated by CoffeeScript 1.9.3
var message;

message = "\n----------------------------------------------------------------\n lxc , openvswitch  packages are needed to run the KaanalNet.\n During this nodejs installation,  \n 1. lxc and  openvswitch debian packages will be installed. \n 2. Base lxc ubuntu image will be installed\n \n This will take  approximately 30mins to complete... -----------------------------------------------------------------\n";

console.log("**************  IMPORTANT NOTE  ***************");

console.log(message);
